name: Scheduled Build

on:
  schedule:
    # 每天格林威治时间 06:00 和 18:00 运行
    # 对应北京时间：每天下午 14:00 和 凌晨 02:00
    - cron: '0 6,18 * * *'
  workflow_dispatch: # 允许您在 GitHub 页面手动点击触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare Pages Build
        run: |
          curl -X POST "${{ secrets.CF_DEPLOY_WEBHOOK }}"
