name: Deploy to GitHub Pages

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    # 每天北京时间 14:00 和 凌晨 02:00 自动运行
    - cron: '0 6,18 * * *'
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Sync Notion
        uses: humbornjo/nobloger@main
        env:
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          NOBLOG_DATABASE_ID: ${{ secrets.NOBLOG_DATABASE_ID }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
